spring:
  datasource:
    url: jdbc:mysql://120.25.148.88:3306/swiperExhibition?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1040679458
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true #下划线驼峰设置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 打印SQL语句